=== northdigital/GridDemo/json-schema/root-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://northdigital.gr/golden-layout.json",

  "type": "object",
  "required": [
    "content"
  ],
  "properties": {
    "content": {
      "$ref": "./content-schema.json"
    },
    "settings": {
      "$ref": "./settings-schema.json"
    },
    "dimensions": {
      "$ref": "./dimension-schema.json"
    },
    "labels": {
      "$ref": "./labels-schema.json"
    }
  },
  "additionalProperties": false
}

=== northdigital/GridDemo/json-schema/test.json
{
  "content": [
    {
      "id": "xxx",
      "type": "row",
      "componentName": "",
      "componentState": {
      },
      "content": [
        {
          "id": "sss",
          "type": "column",
          "componentName": "aaaa",
          "isClosable": true
        }
      ]
    }
  ],
  "dimensions": {
    "dragProxyHeight": 111,
    "minItemHeight": 1111
  },
  "labels": {
    "close": "ssss"
  },
  "settings": {
    "blockedPopoutsThrowError": false,
    "reorderEnabled": false,
    "showMaximiseIcon": true
  }
}
